### ISSUE TITLE
BP-26: Move the distributedlog library to bookkeeper

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#1024]
**BP**

This is the master ticket for tracking BP-26 :

DistributedLog is an extension of Apache BookKeeper, which offers *reopenable* log streams as its storage primitives. It is tightly built over bookkeeper ledgers, and provides an easier-to-use abstraction and api to use. Applications can use *named* log streams rather than *numbered* ledgers to store their data. For example, users can use log streams as files to storge objects, checkpoints and other more general filesystem related use cases.

This BP proposes moving the distributedlog library as part of bookkeeper.

Proposal PR - #1025 

- tasks:
- [x] copy the distributedlog modules under `stream/distributedlog` module. #1068 
- [x] update version of distributedlog modules #1069 
- [x] add the modules to root pom.xml and provide a profile to activate it. #1069
- [x] update CI to have a CI to build the whole suites
- [ ] integrate tutorials and documentation for that.
- [x] integrate into the dist package 
- [x] integrate into docker image
- [x] build the shading jar in bookkeeper way

**Comment by sijie** [comment]
Closed this as all the tasks have been done.
