### ISSUE TITLE
BP-30: BookKeeper Table Service

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#1205]
**BP**

This is the master ticket for tracking BP-30 :

This BP is proposing adding a table (aka key/value) service component as a contrib module to the bookkeeper, which can later be used for metadata storage. This BP together with other BPs forms the ideas of improving metadata management in bookkeeper.

BP Details: https://docs.google.com/document/d/155xAwWv5IdOitHh1NVMEwCMGgB28M3FyMiQSxEpjE-Y/edit#heading=h.56rbh52koe3f

Proposal PR - #1185 

Tasks:

- [x] copy the table service code as the contrib module #1207 
- [x] add the module to profile and only activate it for certain profiles #1216 
- [x] enable ci when code changes touch the module #1216 
- [x] update dist package, docker image
- [ ] documentation

**Comment by eolivelli** [comment]
@sijie  seems we are only lacking the 'documentation' subtask and this will be closed

**Comment by sijie** [comment]
@eolivelli yes the basic functions are there. so we can mark this BP as closed after we have documentation. there will be more improvements/changes in future, but they are separated from this BP.

**Comment by xiemeilong** [comment]
When will this be documented. It seems a useful feature.

**Comment by hsaputra** [comment]
@sijie , @eolivelli - seems like the issue is still missing documentation for the Table service API

**Comment by eolivelli** [comment]
@hsaputra you are totally right !

we really need doc for this feature

cc @Jennifer88huang

**Comment by sijie** [comment]
@hsaputra Apologized that I missed this message! Yes, we still need documentation. The feature is still a beta version. I know your team at Splunk is actively working on it. I am not sure if there are any major API changes or not. We might want to wait for your team to contribute the changes back to the bookkeeper project before @Jennifer88huang starts writing the documentation for it. What do you think?

**Comment by hsaputra** [comment]
HI @sijie , sorry for late response. 
I think it would be ok to wait until the contribution is coming back upstream. It gives motivation to accelerate the initiative.

**Comment by hsaputra** [comment]
HI @sijia-w , @eolivelli - After talking to team at Splunk working on the State Store upgrades, looks like there is no, or very little changes to the Table Service API themselves.

I have filed bug for adding documentation for this new feature. It should be ok for @Jennifer88huang  to start adding doc for this feature.

FYI @merlimat

**Comment by sijie** [comment]
@hsaputra thank you for the heads up!  I will plan that with @Jennifer88huang.

**Comment by HammadB** [comment]
Is there any plan to add documentation for how to use the table service?
