### ISSUE TITLE
Add Checkstyle to the build process

### ISSUE THREAD

**Issue by sigee** [apache/bookkeeper#230]
**Add Checkstyle to the build process**
[Ruleset](https://github.com/apache/incubator-distributedlog/blob/master/distributedlog-build-tools/src/main/resources/distributedlog/checkstyle.xml)

- [X] bookkeeper-benchmark #231
- [X] Stats API for bookkeeper #231
- [x] bookkeeper-stats-providers
  - [X] Stats provider for codahale metrics #231
  - [X] Stats provider for Finagle stats #231
  - [X] Stats provider for Prometheus #231
  - [X] Stats provider for twitter-ostrich package #231
  - [X] Stats provider for twitter-stats package #231
- [ ] compability dependencies
  - [ ] bookkeeper-server-compat400
  - [ ] bookkeeper-server-compat410
  - [ ] bookkeeper-server-compat420
- [ ] bookkeeper-server
  - [X] org.apache.bookkeeper.auth #234
  - [X] org.apache.bookkeeper.bookie #234
  - [ ] org.apache.bookkeeper.client
  - [ ] org.apache.bookkeeper.conf
  - [x] org.apache.bookkeeper.feature #675 
  - [ ] org.apache.bookkeeper.meta
  - [ ] org.apache.bookkeeper.metastore
  - [ ] org.apache.bookkeeper.net
  - [x] org.apache.bookkeeper.processor #675 
  - [ ] org.apache.bookkeeper.proto
  - [ ] org.apache.bookkeeper.replication
  - [ ] org.apache.bookkeeper.sasl
  - [x] org.apache.bookkeeper.shims.zk #675 
  - [x] org.apache.bookkeeper.stats #675 
  - [x] org.apache.bookkeeper.streaming #675 
  - [ ] org.apache.bookkeeper.util
  - [x] org.apache.bookkeeper.versioning #675 
  - [x] org.apache.bookkeeper.zookeeper #675

**Comment by jiazhai** [comment]
👍, It is clear to have them tracked here.

**Comment by sijie** [comment]
#231 is merged.

**Comment by sijie** [comment]
reopened this. it is a master ticket.

**Comment by sijie** [comment]
@sigee are you still working on this? shall other contributors help pick up this as well?

**Comment by sijie** [comment]
ping @sigee

**Comment by sigee** [comment]
@sijie,
I couldn't finish it. I've got a new project at my job, so I'm very busy, but I'd like to finish this issue as soon as possible.

**Comment by sijie** [comment]
this issue has been a while. we might consider completing it ASAP. it is halfway through the process. I am going to pick up one each week.
