### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#318]
Created a master issue for tracking any questions, improvements regarding the new website/documentation.

**Tasks**:
- [x] script for publishing website to staging (for reviews) and apache #320 
- [x] ci job to automatically publish website to apache once the pull request is merged #323
- [x] add redirections for documentation from old releases. #324
- [x] Update "who are we?" #321 
- [x] how to manage documentation between releases #325 
- [x] add slack channel #333
- [x] add a releases page #344 

**Bugs**:

**Improvements**:

**Comment by sijie** [comment]
This issue was for the new website. all the sub-tasks have been completed. close it.
