### ISSUE TITLE
Docker Image v1.0

### ISSUE THREAD

**Issue by caiok** [apache/bookkeeper#330]
This issue is for track the steps involved in order to implement the version 1.0 of the official bookkeeper docker image. I tried to enlist them in order of priority:

- [x] #197: first docker build draft
- [ ] #338: add first draft including community suggestions
- [ ] #327: drop versions and Alpine support (the first one to do before moving on)
- [ ] #329: gracefully handle start and stop bookie gracefully
- [ ] #260: provide a way to pass any desired configuration property via ENV vars
- [ ] #289: make docker image build based on master latest code
- [ ] #292: setup docker automated build on Apache DockerHub account
- [ ] #288: (to be dropped?) provide a template related way to handle different version status/help-needed

Following steps are optional:
- [ ] #261: create a tutorial dice application docker build
- [ ] #328: add a Docker Compose example file

**Comment by caiok** [comment]
@jiazhai opened #335 with the same aim of this issue
