### ISSUE TITLE
Docker Image: tracking sub issues

### ISSUE THREAD

**Issue by jiazhai** [apache/bookkeeper#335]
Thanks to @sijie's summary, Here is the requirement discussed out in community meeting.

- follow what other apache projects are doing [zeppelin](https://issues.apache.org/jira/browse/INFRA-12781)
- using docker autobuild
- dockerfile is to download official bk release image
- remove versions. docker autobuild will look for docker file location and release tags.
- os versions. let's stick to centos-7 and jdk-8.
- configuration: 1) allow providing a configuration from a mounted volume 2) if no configuration file is provided, it will use the template packaged in the binary and take the ENV variables that start with "bk_"
- entry point: we need an entry point to start and stop bookie gracefully
- documentation: docker-compose file to start a cluster for testing
- optional: k8s and dcos instructions (can be separate pull requests)

Thanks @caiok for create the sub tasks, regarding above requirements, And following @caiok 's suggestion, Here is a step by step work based on the time and priority, feel free to comment and change it if it is not reasonable.
First:
- [X] [338](https://github.com/apache/bookkeeper/issues/338): Docker image: Add first draft including community suggestions.
    - [X] [327](https://github.com/apache/bookkeeper/issues/327): Docker image: Drop versions and Alpine support.
    - [X] [329](https://github.com/apache/bookkeeper/issues/329): Docker image: gracefully handle start and stop bookie gracefully.
    - [X] [260](https://github.com/apache/bookkeeper/issues/260): Docker image: provide a way to pass any desired configuration property via ENV vars.

Second:
- [X] [292](https://github.com/apache/bookkeeper/issues/292): Docker image: setup docker automated build on Apache DockerHub account.
- [x] [336](https://github.com/apache/bookkeeper/issues/336): Docker image: DCOS package update and instructions.
- [X] [337](https://github.com/apache/bookkeeper/issues/337): Docker image: K8s for bookkeeper and instructions on usage.
- [x] [289](https://github.com/apache/bookkeeper/issues/289): Docker image: make docker image build based on master latest code.

Third step:
- [x] [261](https://github.com/apache/bookkeeper/issues/261): Docker image: create a tutorial dice application docker build.
- [x] [328](https://github.com/apache/bookkeeper/issues/328): Docker image: add a Docker Compose example file.

**Comment by caiok** [comment]
Hi @jiazhai maybe this is a duplicate of #330? I'm ok with closing #330, take a look at it and merge with your own list (I think we should distinguish between "must have" issues and "nice to have" ones and to sort by priority whenever is possible)

**Comment by jiazhai** [comment]
Hi @caiok, Thanks for the reminder, sorry for not looking into #330 before creating this issue, from its name, I thought it is only related to PR #197.  
Seems there are some differences, I will merge #330, and add more details into this issue.

**Comment by eolivelli** [comment]
@jiazhai  @sijie  should we create a Github label "docker" ? there are plenty of issues/pull requests and I think it is worth a label so that contributors interested in this topic will find issues quickly

**Comment by sijie** [comment]
@eolivelli +1

**Comment by sijie** [comment]
Closed this tracking issue since all sub-tasks are done.

**Comment by eolivelli** [comment]
This is what we have currently 
https://issues.apache.org/jira/browse/INFRA-14756
