### ISSUE TITLE
Improve the function: set dir name to store index files.

### ISSUE THREAD

**Issue by StevenLuMT** [apache/bookkeeper#3419]
This issue is used to track prs that need to be included in the BookKeeper 4.15.1/4.16.0 release.

- [x] [Basic function: directories to store index files #3352](https://github.com/apache/bookkeeper/pull/3352)
- [x] [add and check indexDirs in Cookie meta #3372](https://github.com/apache/bookkeeper/pull/3372)
- [x] [Add a param in cookie_generate for updating indexDirs #3380](https://github.com/apache/bookkeeper/pull/3380)
- [x] [stage 3~4 : Add indexDirs in statsLogger, add indexDirs's Listener. #3397](https://github.com/apache/bookkeeper/pull/3397)
- [x] [stage 5: bugfix indexDirs for readLedgerIndexEntries #3398](https://github.com/apache/bookkeeper/pull/3398)
- [x] [stage 6: bugfix indexDirs for LocationsIndexRebuildOp #3399](https://github.com/apache/bookkeeper/pull/3399)
- [x] [stage 7: print indexDirs's info when start bookie #3401](https://github.com/apache/bookkeeper/pull/3401)
- [x] [stage 8: bugfix indexDirs for LedgersIndexCheckOp #3402](https://github.com/apache/bookkeeper/pull/3402)
- [x] [stage 9: bugfix indexDirs for LedgersIndexRebuildOp #3403](https://github.com/apache/bookkeeper/pull/3403)
- [x] [stage 10: bugfix indexDirs for ConvertToInterleavedStorageCommand #3409](https://github.com/apache/bookkeeper/pull/3409)
- [x]  [indexDir compatible fix for issue 3430](https://github.com/apache/bookkeeper/pull/3433)
