### ISSUE TITLE
Tracking unit test failures

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#463]
Here is a log for recently build for your reference:
https://builds.apache.org/job/bookkeeper-precommit-pullrequest/307/#showFailuresLink
```    
    org.apache.bookkeeper.client.TestFencing.testManyOpenParallel
    org.apache.bookkeeper.tls.TestTLS.testTLSClientButOnlyFewTLSServers
    org.apache.bookkeeper.bookie.CompactionByBytesTest.testMinorCompactionWithNoWritableLedgerDirsButIsForceGCAllowWhenNoSpaceIsSet
    org.apache.bookkeeper.bookie.CompactionByBytesTest.testDisableCompaction
    org.apache.bookkeeper.bookie.CompactionByEntriesTest.testMinorCompactionWithNoWritableLedgerDirsButIsForceGCAllowWhenNoSpaceIsSet
    org.apache.bookkeeper.bookie.CompactionByEntriesTest.testDisableCompaction
    org.apache.bookkeeper.tls.TestTLS.testBookieAuthPluginDenyAccesstoClientWithoutTLSAuthentication
    org.apache.bookkeeper.tls.TestTLS.testClientWantsTLSNoServersHaveIt
```

Would like to use this issue for unit test failure tracking, 
hope we could fix it soon to make a stable and clean build, 
and feel free to edit this to add the un-tracked failures :

- [x] #462 : TestTLS failures , 
- [x] #459 : CompactionTest failures , PR #460 is for the fix.
- [ ] #415 :  Test failure in UpdateCookieCmdTest  ,
- [x] #343: TestFencing.testManyOpenParallel ,
- [X] #414:  Test failure in UpdateLedgerOpTest,
- [X] #390: Test errors in TestRackawareEnsemblePlacementPolicyUsingScript
- [X] #479: CompactionTest#testCompactionWithEntryLogRollover failed

**Comment by eolivelli** [comment]
We can make it blocker for 4.6

**Comment by sijie** [comment]
#462 and #343 all have fixes now.

I can't reproduce `UpdateCookieCmdTest`. I am suspecting it is related to the binding address.

**Comment by zhaijack** [comment]
Thanks for the great help @sijie .
